name: retailanalyticsapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  mobile_scanner: ^7.1.4
  http_parser: ^4.0.2
  provider: ^6.0.0
  image_picker: ^1.0.4
  pdf: ^3.10.4
  printing: ^5.11.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true